name: Pipeline Super

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/penugasan_cicd:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Decode SSH private key
        run: echo "${{ secrets.SSHKEY }}" | base64 -d > ~/.ssh/id_rsa
      - name: Set permissions for SSH private key
        run: chmod 600 ~/.ssh/id_rsa
      - name: SSH to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key_path: ~/.ssh/id_rsa
          script: |
            if [ ! -d "/home/ubuntu/cicd" ]; then
              git clone https://github.com/SchoolBoyJoJo/Penugasan-CICD-AJK.git /home/ubuntu/cicd
            fi
            cd /home/ubuntu/cicd  # Navigate to the deployment directory
            git pull origin main  # Pull the latest changes from the main branch
            docker-compose down  # Stop and remove existing containers
            docker-compose up -d --build  # Recreate containers using the updated images and build if necessary
